# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a815e4fc1bf09ad876b03a986c0a2b06b33b7f606ccbf7a5f1eb96ef20ba61737520094efc69efcc815e85353f669d6f06c3e442dfd620ed87efefde3a052aa

test:
  secret_key_base: 5aee9230364279cc972e6f576edc4769ec524c727bf0d98383c2940681cbb4f72ef597b265ad1fba9242e9d7e3510a7a25b454805ee153f1f41d51b90df87226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
